description: >
  Create package with SQL files from repository
  Then upgrade to this package
usage:
  version: 2.1
  orbs:
    dbm-test2: dbm/dbm-test2@0.0.7

jobs:
  dbm-deploy:
          docker:
            - image: cimg/openjdk:16.0.2
          steps:
            - checkout
            - dbm-test2/download-automation-jar
            - dbm-test2/create-manifest-file:
                path_to_scripts_folder: "V3"
            - run:
              command: cd V3&&zip -r ../V3.zip *&&cd ..
              name: Zip the package
            - dbm-test2/package:
                project_name: "DEMO"
                file_path: "V3.zip"
                server_address: "dbm.automation.host:8017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/pre-check:
                project_name: "DEMO"
                package_name: "V3"
                server_address: "dbm.automation.host:8017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"
            - dbm-test2/upgrade:
                project_name: "DEMO"
                environment_name: "Release Source"
                package_name: "V3"
                server_address: "dbm.automation.host:8017"
                auth_type: "DBmaestroAccount"
                username: "test@dbmaestro.com"

workflows:
  test-run:
    jobs:
      - dbm-deploy
